name: Extract DLLs
on: [push, workflow_dispatch]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Recombine Assets
        run: |
          cat hook_part_* > hook.zip
          unzip -o hook.zip
          find . -name "libil2cpp.so" -exec mv {} . \;
          find . -name "global-metadata.dat" -exec mv {} . \;

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Run Dumper (EXE Mode)
        run: |
          # Dumper download (Hum zip version uthayenge jisme EXE ho)
          wget -q https://github.com/Perfare/Il2CppDumper/releases/download/v6.7.40/Il2CppDumper-v6.7.40.zip
          unzip -o Il2CppDumper-v6.7.40.zip
          
          # Dotnet ke zariye EXE chalana (Sabse stable method)
          # 'echo -e' commands auto-input ke liye hain agar dumper kuch pooche
          echo -e "\n" | dotnet Il2CppDumper.dll libil2cpp.so global-metadata.dat ./Output
          
      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Extracted-DLLs
          path: ./Output/
