name: Extract DLLs
on: [push, workflow_dispatch]

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Recombine and Unzip
        run: |
          # Sabhi parts ko jodo
          cat hook_part_* > hook.zip
          # Unzip karo aur files ko current folder mein force move karo
          unzip -o hook.zip
          find . -name "libil2cpp.so" -exec mv {} . \;
          find . -name "global-metadata.dat" -exec mv {} . \;
          # Check karne ke liye ki files asli hain (size dikhayega)
          ls -lh libil2cpp.so global-metadata.dat

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Run Dumper
        run: |
          # Dumper download aur setup
          wget -q https://github.com/Perfare/Il2CppDumper/releases/download/v6.7.40/Il2CppDumper-v6.7.40.zip
          unzip -q Il2CppDumper-v6.7.40.zip
          chmod +x Il2CppDumper
          
          # Dumper ko run karna (Explicitly files specify karke)
          ./Il2CppDumper libil2cpp.so global-metadata.dat ./Output || echo "Dumper failed but checking why..."
          
      - name: Upload DLLs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Extracted-DLLs
          path: ./Output/DummyDll/
